# Generated by Django 5.2 on 2026-03-18 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Theatre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=300)),
                ('address', models.TextField()),
                ('total_seats', models.IntegerField()),
                ('seats_layout', models.JSONField(default=dict, help_text='JSON format for seat layout')),
                ('facilities', models.JSONField(default=list, help_text='List of facilities like Parking, Food Court, etc.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Screen name like Screen 1, Screen 2, etc.', max_length=100)),
                ('screen_type', models.CharField(choices=[('standard', 'Standard'), ('3d', '3D'), ('imax', 'IMAX'), ('4dx', '4DX')], default='standard', max_length=20)),
                ('total_seats', models.IntegerField()),
                ('seats_layout', models.JSONField(default=dict)),
                ('theatre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screens', to='theatre.theatre')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
