# Generated by Django 5.2 on 2026-03-18 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('admin', 'Admin'), ('theatre_owner', 'Theatre Owner'), ('staff', 'Staff')], default='customer', max_length=20),
        ),
    ]
